In [ ]:
#라벨인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
#지알아서 라벨링 함

[0 1 4 2 2 3 3]


In [4]:
print(encoder.classes_)

['TV' '냉장고' '선풍기' '에어컨' '컴퓨터']


In [ ]:
#원핫인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

items = np.array(items).reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(7, 5)
