In [ ]:
## 라벨인코딩
from sklearn.preprocessing import LabelEncoder
# 문자열 형태의 범주형 데이터를 숫자로 바꾼다

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

encoder = LabelEncoder()
# 라벨 인코딩을 수행할 객체

encoder.fit(items)
# items 안에 어떤 종류의 값들이 존재하는지 파악하는 과정
# 라벨인코더는 items 안의 클래스들을 정렬한 뒤 각각 숫자를 부여함 --> 한글은 가나다 순으로 정렬
# 얘는 변환 규칙을 학습하는 부분


labels = encoder.transform(items)
# fit에서 정한 규칙을 실제 데이터에 적용해서 문자열을 숫자로 변환함
# 얘는 그 규칙으로 실제 값을 변환하는 부분

print(labels)


[0 1 4 2 2 3 3]


In [ ]:
print(encoder.classes_)
# LabelEncoder가 어떤 범주들을 인식했고, 어떤 순서로 번호를 붙였는지 확인하는 코드

['TV' '냉장고' '선풍기' '에어컨' '컴퓨터']


In [ ]:
## 원핫인코딩
# 문자열 범주를 숫자 벡터로 바꾸는 과정
# 예를들어, TV --> [1, 0, 0, 0, 0] 이런식으로 지만 1
from sklearn.preprocessing import OneHotEncoder
# OneHotEncoder를 가져온다
import numpy as np

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

print(np.array(items))

items = np.array(items).reshape(-1, 1)
# items를 numpy 배열로 바꾸고, 그걸 2차원 형태로 바꿈
# -1의 뜻은 '행 개수는 데이터 개수에 맞게 알아서 해라', 1의 뜻은 열은 한개로 만들어라는 뜻
# 그러면 원래는 (7,)형태였던 것이 (7,1)이 된다

oh_encoder = OneHotEncoder()
# 원핫 인코딩을 수행할 객체 생성

oh_encoder.fit(items)
# 원핫 인코더가 items 안에 어떤 종류의 값이 있는지 파악 및 학습
# 그리고 내부적으로 각 항목에 대응하는 열을 만든다.
# TV 냉장고 선풍기 에어컨 컴퓨터 <-- 이렇게 5개의 열이 만들어진다

oh_labels = oh_encoder.transform(items)
# 실제 데이터를 원핫인코딩 하는 부분
# 예를들어, TV --> [1, 0, 0, 0, 0] 이런식으로.

print(oh_labels.toarray())
# 왜 바로 출력하지 않고 toarray를 쓰나?
# 사람이 보기 편하게 일반 배열로 바꾸기 위함
print(oh_labels.shape)

['TV' '냉장고' '컴퓨터' '선풍기' '선풍기' '에어컨' '에어컨']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(7, 5)
