In [2]:
import numpy as np #numpy ->np, pandas ->pd 이거 convention임. 딴걸로 해도 되긴 한데, 따르는게 좋다

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
li1= [
    [1,2,3],
    [4,5,6],
    [1,2,3],
    [4,5,6],
    [1,2,3],
    [4,5,6],
    [1,2,3],
    [4,5,6],
    [1,2,3],
    [4,5,6]
]

print(li1)
print(type(li1))
#불편, 리스트가 아래로 가는게 편한데 한줄로 나오니까 불편 --> 리스트로 안하고 ndarray로 하는 이유임. 또한, ndarray로 하면 행렬임

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
<class 'list'>


In [5]:
arr3 = np.array([
    [[1,2],
     [3,4]],
    [[5,6],
     [7,8]]
])

print(arr3)
print(type(arr3))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [6]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [7]:
ones = np.ones((2, 3))

print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
range_arr = np.arange(1, 10, 2)
print(range_arr)

[1 3 5 7 9]


In [18]:
# 데이터 타입

정수 = np.array([1, 2, 3, 4, 5])
print(정수.dtype)
print(정수)

int64
[1 2 3 4 5]


In [19]:
실수 = np.array([1.5, 2.5, 3.5])
print(실수.dtype)
print(실수)

float64
[1.5 2.5 3.5]


In [11]:
# 배열 속성
arr1 = np.array([1, 2, 3, 4])
arr1.shape

(4,)

In [12]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

arr2.shape

(2, 3)

In [21]:
arr3 = np.array([
    [[1,2,3,4],
     [3,4,5,6]],
    [[5,6,7,8],
     [7,8,9,10]],
    [[5,6,7,8],
     [7,8,9,10]]
])

arr3.shape

(3, 2, 4)

In [22]:
# ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


1
2
3


In [15]:
#size - 배열의 총 요소 수를 알려줌

arr1 = np.array([1, 2, 3, 4])
print(arr1.size)

4


In [16]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2.size)

6


In [17]:
arr3 = np.array([
    [[1,2],
     [3,4]],
    [[5,6],
     [7,8]]
])

print(arr3.size)

8
