In [1]:
# 인덱싱과 슬라이싱

import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[1])
print(arr[1, 2]) #1행 2열 (=2,3)

[4 5 6]
6


In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [10]:
cond = arr > 2
# = arr[arr > 2]
arr[cond]

array([3, 4, 5])

In [ ]:
cond = (arr > 2) & (arr < 5) #기본문법에서는 ()안해도 됐는데, numpy에서는 () 쳐줘야함
print(arr[cond])

[3 4]


In [ ]:
# 통계함수
## 평균, 분산, 표준편차, 중앙값, 최빈값

arr = np.array([1, 2, 3, 4])

print("합계: ", arr.sum())
print("평균: ", arr.mean())
print("분산: ", arr.var())
print("분산: ", np.var(arr))
print("표준편차: ", arr.std())
print("표준편차: ", np.std(arr))
print("중앙값: ", np.median(arr))


합계:  10
평균:  2.5
분산:  1.25
분산:  1.25
표준편차:  1.118033988749895
표준편차:  1.118033988749895
중앙값:  2.5
